/**
 * Primitives shared by every domain schema.
 *
 * Rule for this whole directory: zod is the single source of truth. Every
 * exported TS type is derived with `z.infer`. Do not hand-write a type that a
 * schema already describes.
 */
import { z } from 'zod';

/**
 * ISO-8601 timestamp, e.g. `2026-08-07T10:31:00.000Z`.
 *
 * Deliberately lenient (`string`, not `z.iso.datetime()`): these values round
 * trip through SQLite as TEXT and are also written by the agent, and a strict
 * regex here turns a cosmetic difference into a data-loss bug. Produce them
 * with {@link nowIso}.
 */
export const IsoDateTimeSchema = z
  .string()
  .min(1)
  .describe('ISO-8601 timestamp');
export type IsoDateTime = z.infer<typeof IsoDateTimeSchema>;

/** Opaque identifier. Generated by `infra/crypto.randomId()`. */
export const IdSchema = z.string().min(1).describe('Opaque identifier');
export type Id = z.infer<typeof IdSchema>;

export type JsonValue =
  string | number | boolean | null | JsonValue[] | { [key: string]: JsonValue };

/** Free-form JSON blob. Stored as TEXT, parsed on read. */
export const JsonValueSchema: z.ZodType<JsonValue> = z.lazy(() =>
  z.union([
    z.string(),
    z.number(),
    z.boolean(),
    z.null(),
    z.array(JsonValueSchema),
    z.record(z.string(), JsonValueSchema),
  ]),
);

export const JsonObjectSchema = z.record(z.string(), z.unknown());
export type JsonObject = z.infer<typeof JsonObjectSchema>;

export const LOG_LEVELS = ['debug', 'info', 'warn', 'error'] as const;
export const LogLevelSchema = z.enum(LOG_LEVELS);
export type LogLevel = z.infer<typeof LogLevelSchema>;

/**
 * Token / cost accounting for a run or step. Every field optional because
 * engines report different subsets.
 */
export const UsageSchema = z.object({
  model: z.string().optional(),
  inputTokens: z.number().int().nonnegative().optional(),
  outputTokens: z.number().int().nonnegative().optional(),
  cacheReadTokens: z.number().int().nonnegative().optional(),
  cacheCreationTokens: z.number().int().nonnegative().optional(),
  totalCostUsd: z.number().nonnegative().optional(),
  durationMs: z.number().int().nonnegative().optional(),
  turns: z.number().int().nonnegative().optional(),
});
export type Usage = z.infer<typeof UsageSchema>;

/** Standard shape for a paginated list request. */
export const PageQuerySchema = z.object({
  limit: z.number().int().positive().max(500).default(50),
  offset: z.number().int().nonnegative().default(0),
});
export type PageQuery = z.infer<typeof PageQuerySchema>;
export type PageQueryInput = z.input<typeof PageQuerySchema>;

/** Standard shape for a paginated list response. */
export interface Page<T> {
  items: T[];
  total: number;
  limit: number;
  offset: number;
}

/** Current time as an {@link IsoDateTime}. */
export function nowIso(): IsoDateTime {
  return new Date().toISOString();
}

/* ------------------------------------------------------------------ */
/* Patch schemas                                                       */
/* ------------------------------------------------------------------ */

/**
 * Peel `.default()` / `.prefault()` wrappers off a schema type.
 *
 * Unwrapping a default does not change the *output* type — `ZodDefault<T>` and
 * `T` infer the same thing — so this only changes runtime behaviour, never the
 * shape a caller sees.
 */
type StripDefault<T> =
  T extends z.ZodDefault<infer Inner> ? StripDefault<Inner> : T;

type PatchShape<S extends z.ZodRawShape> = {
  [K in keyof S]: z.ZodOptional<StripDefault<S[K]> & z.ZodType>;
};

/** Runtime half of {@link StripDefault}. Also handles `prefault`. */
function stripDefault(schema: z.ZodType): z.ZodType {
  let current = schema;
  for (;;) {
    const kind = (current as unknown as { _zod?: { def?: { type?: string } } })
      ._zod?.def?.type;
    if (kind !== 'default' && kind !== 'prefault') return current;
    current = (current as unknown as { unwrap(): z.ZodType }).unwrap();
  }
}

/**
 * Build a **patch** schema: every field optional, and every `.default(...)`
 * stripped so an absent field stays absent.
 *
 * Use this instead of `.partial()` for anything that describes a partial
 * update. `.partial()` only makes the *input* optional — zod still applies the
 * field's default on the way out, so
 *
 * ```ts
 * GoalSchema.omit({...}).partial().parse({ title: 'x' })
 * // => { title: 'x', description: '', status: 'active', order: 0 }
 * ```
 *
 * A store that spreads that over the stored row silently blanks the
 * description and reorders the goal. This helper yields `{ title: 'x' }`, so
 * "not mentioned" and "set to the default" stay distinguishable — which is the
 * entire semantic difference between a patch and a replace.
 */
export function patchSchema<T extends z.ZodObject<z.ZodRawShape>>(
  schema: T,
): z.ZodObject<PatchShape<T['shape']>> {
  const next: Record<string, z.ZodType> = {};
  for (const [key, field] of Object.entries(
    schema.shape as Record<string, z.ZodType>,
  )) {
    next[key] = stripDefault(field).optional();
  }
  return z.object(next) as unknown as z.ZodObject<PatchShape<T['shape']>>;
}
