/**
 * Primitives shared by every domain schema.
 *
 * Rule for this whole directory: zod is the single source of truth. Every
 * exported TS type is derived with `z.infer`. Do not hand-write a type that a
 * schema already describes.
 */
import { z } from 'zod';

/**
 * ISO-8601 timestamp, e.g. `2026-08-07T10:31:00.000Z`.
 *
 * Deliberately lenient (`string`, not `z.iso.datetime()`): these values round
 * trip through SQLite as TEXT and are also written by the agent, and a strict
 * regex here turns a cosmetic difference into a data-loss bug. Produce them
 * with {@link nowIso}.
 */
export const IsoDateTimeSchema = z
  .string()
  .min(1)
  .describe('ISO-8601 timestamp');
export type IsoDateTime = z.infer<typeof IsoDateTimeSchema>;

/** Opaque identifier. Generated by `infra/crypto.randomId()`. */
export const IdSchema = z.string().min(1).describe('Opaque identifier');
export type Id = z.infer<typeof IdSchema>;

export type JsonValue =
  string | number | boolean | null | JsonValue[] | { [key: string]: JsonValue };

/** Free-form JSON blob. Stored as TEXT, parsed on read. */
export const JsonValueSchema: z.ZodType<JsonValue> = z.lazy(() =>
  z.union([
    z.string(),
    z.number(),
    z.boolean(),
    z.null(),
    z.array(JsonValueSchema),
    z.record(z.string(), JsonValueSchema),
  ]),
);

export const JsonObjectSchema = z.record(z.string(), z.unknown());
export type JsonObject = z.infer<typeof JsonObjectSchema>;

export const LOG_LEVELS = ['debug', 'info', 'warn', 'error'] as const;
export const LogLevelSchema = z.enum(LOG_LEVELS);
export type LogLevel = z.infer<typeof LogLevelSchema>;

/**
 * Token / cost accounting for a run or step. Every field optional because
 * engines report different subsets.
 */
export const UsageSchema = z.object({
  model: z.string().optional(),
  inputTokens: z.number().int().nonnegative().optional(),
  outputTokens: z.number().int().nonnegative().optional(),
  cacheReadTokens: z.number().int().nonnegative().optional(),
  cacheCreationTokens: z.number().int().nonnegative().optional(),
  totalCostUsd: z.number().nonnegative().optional(),
  durationMs: z.number().int().nonnegative().optional(),
  turns: z.number().int().nonnegative().optional(),
});
export type Usage = z.infer<typeof UsageSchema>;

/** Standard shape for a paginated list request. */
export const PageQuerySchema = z.object({
  limit: z.number().int().positive().max(500).default(50),
  offset: z.number().int().nonnegative().default(0),
});
export type PageQuery = z.infer<typeof PageQuerySchema>;
export type PageQueryInput = z.input<typeof PageQuerySchema>;

/** Standard shape for a paginated list response. */
export interface Page<T> {
  items: T[];
  total: number;
  limit: number;
  offset: number;
}

/** Current time as an {@link IsoDateTime}. */
export function nowIso(): IsoDateTime {
  return new Date().toISOString();
}
